<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
    </parent>

    <groupId>info.jab.ms</groupId>
    <artifactId>spring-boot-streaming-example</artifactId>
    <version>0.1.0</version>
    <packaging>pom</packaging>

    <name>spring-boot-streaming-example-parent</name>
    <description>Parent build for Spring Boot streaming examples</description>

    <modules>
        <module>openapi-specs</module>
        <module>spring-boot-weflux-consumer</module>
        <module>spring-boot-mvc-streaming-consumer</module>
        <module>spring-boot-mvc-sse-emitter-consumer</module>
    </modules>

    <properties>
        <java.version>25</java.version>
        <maven.compiler.release>25</maven.compiler.release>
        <maven-dependency-plugin.version>3.9.0</maven-dependency-plugin.version>
        <openapi-generator-maven-plugin.version>7.23.0</openapi-generator-maven-plugin.version>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <swagger-annotations-jakarta.version>2.2.52</swagger-annotations-jakarta.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>info.jab.ms</groupId>
                <artifactId>openapi-specs</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations-jakarta</artifactId>
                <version>${swagger-annotations-jakarta.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>${maven-dependency-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.openapitools</groupId>
                    <artifactId>openapi-generator-maven-plugin</artifactId>
                    <version>${openapi-generator-maven-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
