micronaut.application.name=micronaut-streaming-consumer
micronaut.server.port=8085
micronaut.server.host=0.0.0.0
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allowed-origins[0]=http://localhost:8080
micronaut.server.cors.configurations.web.allowed-origins[1]=http://127.0.0.1:8080
micronaut.server.cors.configurations.web.allowed-methods[0]=GET
micronaut.server.netty.graceful-shutdown-quiet-period=2s
micronaut.server.netty.graceful-shutdown-timeout=30s
micronaut.router.static-resources.default.enabled=true
micronaut.router.static-resources.default.paths[0]=classpath:META-INF/resources
micronaut.router.static-resources.default.mapping=/**
endpoints.health.enabled=true
endpoints.health.sensitive=false

wikimedia.base-url=https://stream.wikimedia.org
wikimedia.recent-change-path=/v2/stream/recentchange
