quarkus.application.name=quarkus-streaming-consumer
quarkus.http.port=8084
quarkus.http.host=0.0.0.0
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:8080,http://127.0.0.1:8080
quarkus.http.cors.methods=GET
quarkus.shutdown.timeout=30S

wikimedia.base-url=https://stream.wikimedia.org
wikimedia.recent-change-path=/v2/stream/recentchange
